apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crystolia-platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ShaiMullo/crystolia-app.git
    targetRevision: deploy/production
    path: helm/crystolia-chart
    helm:
      parameters:
      - name: backend.service.port
        value: "4000"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
