apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crystolia-platform
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ShaiMullo/crystolia-app.git
    targetRevision: main
    path: charts/crystolia
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
